### PR TITLE
add penalty factor named pfl1 and functions are modified correspondingly

### LINKED ISSUE #26: Allow for weights on the ell-1 part

### PR DESCRIPTION
**Pull request by Xiaoxuan1121**

### CODE REVIEW

**Comment by Xiaoxuan1121** [comment]
I'm still seeing the stop signs in the "sparsegl_init.c"  after I added parameter pfl1. I also tried to reclone the repo again, opened the original file from main and the stop signs were there as well from my local.

**Comment by dajmcdon** [comment]
I'm less concerned with the error signs from the R debugger. That could occur for many reasons having nothing to do with the validity of the code.

* Does this implementation work? If you give it meaningful weights, do you get the expected result? Your tests only check for simple bugs but not functionality.
* You should also make sure that you don't modify files from the existing `main` branch. I moved the JSS stuff out. Here you add it back. You have to merge main onto your branch before doing a PR.

**Comment by Xiaoxuan1121** [comment]
I didn't see JSS anywhere on my local or on this branch from my last commit? Actually I cloned the repo again after you removed JSS from main.

**Comment by dajmcdon** [comment]
Please click the "Files changed" tab and ensure that only the relevant files are adjusted.

**Comment by dajmcdon** [comment]
I can't merge this to `main` because it will delete improvements that have been made there. I changed some of the code so that the mse gets calculated in fortran and returned. But you've deleted them on your branch. You need to ensure that your PR doesn't kill useful functionality when adding new functionality.

**Pull request closed without merging**
