### PR TITLE
add all required files to compile PDF

### PR DESCRIPTION
**Pull request by Xiaoxuan1121**
There are two datasets I pushed in this PR: running-time-records-current and running-time-records-previous. I have been generating datasets for many times and weirdly, there is a sudden drop when increasing n to pretty large numbers for logistic regression model (demonstrated in -current one), but it never happens from previously (I still save the records as -previous).

### CODE REVIEW

**Comment by dajmcdon** [comment]
Two issues
* this version seems to be running the simulation. Didn't you pull out the code into a separate script and load it in the markdown before?
* Second, the version of the package on `main` uses `sparsegl(..., family = c("gaussian","binomial"))` rather than `loss` as an argument (to match all the other functions in most of R). Can you adjust that in the code? And the vignette as well (separate branch please).

**Review by dajmcdon — CHANGES_REQUESTED** [review]
Two issues

* this version seems to be running the simulation. Didn't you pull out the code into a separate script and load it in the markdown before?
* Second, the version of the package on main uses `sparsegl(..., family = c("gaussian","binomial"))` rather than `loss` as an argument (to match all the other functions in most of R). Can you adjust that in the code? And the vignette as well (separate branch please).

**Comment by Xiaoxuan1121** [comment]
> Two issues
> 
> * this version seems to be running the simulation. Didn't you pull out the code into a separate script and load it in the markdown before?
> * Second, the version of the package on main uses `sparsegl(..., family = c("gaussian","binomial"))` rather than `loss` as an argument (to match all the other functions in most of R). Can you adjust that in the code? And the vignette as well (separate branch please).

For the first issue, I don't really know why this happens. If you go to the history and check the jss-sparsegl.Rmd version with commit message "add all required files to compile PDF" in this branch, then that one is what I meant to update. I remember there is a conflict in this file so I fixed and merged it, and then it pulled everything from main again....

**Comment by dajmcdon** [comment]
I'm guessing because I reverted the previous PR merge (undo). You probably need to go to the old commit on your local version, create a new branch, and make a PR from that instead of from this branch.

**Pull request closed without merging**
