### PR TITLE
Jss continue

### PR DESCRIPTION
**Pull request by Xiaoxuan1121**

### CODE REVIEW

**Comment by dajmcdon** [comment]
please merge `main` into this branch and resolve conflicts. The only files here should really be the `.Rmd` and the `sparsegl.bib`.

**Review by dajmcdon — CHANGES_REQUESTED** [review]
See comment. Merge `main` into this branch

**Review by dajmcdon — APPROVED** [review]

**Comment by dajmcdon** [comment]
@Xiaoxuan1121 this is missing the Rscript and the .rds file for the comparison. You need those files as well. I should be able to rebuild the manuscript locally by knitting the .Rmd. And it should be able to run in less than 1 minute.

**Comment by dajmcdon** [comment]
You should make the changes and open a new PR.

**Comment by Xiaoxuan1121** [comment]
@dajmcdon  To make this clear, there should be 4 files under the folder jss-sparsegl in total: jss-sparsegl.Rmd, sparsegl.bib, Rscript for plotting and the generated dataset. Is this correct?

**Comment by dajmcdon** [comment]
Possibly. You need to make sure that it has everything needed in order to build the pdf. I should be able to pull this branch and create the pdf.

**Pull request merged**
